# Generated by Django 3.1.3 on 2020-11-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=80)),
                ('date_created', models.DateField()),
                ('path', models.CharField(max_length=80)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customgroups')),
            ],
        ),
    ]
